ignore:
  # From rouille - The Zarf injector does not expose endpoints that use multipart form data
  - vulnerability: GHSA-mc8h-8q98-g5hr

  # From helm - This behavior was introduced intentionally, and cannot be removed without breaking backwards compatibility (some users may be relying on these values).
  - vulnerability: GHSA-jw44-4f3j-q396
