[package.create.set]
# The image reference to use for the Zarf agent, defaults to a locally built image
agent_image_domain = 'ghcr.io/'
agent_image = 'defenseunicorns/zarf/agent'
agent_image_tag = 'local'

# Tag for the zarf injector binary to use
injector_version = '2024-05-13'
injector_amd64_shasum = 'c648fbd4ced4522ef2f8aa93c0f202a92dbf9dd742eccfe167160da3b02e2a17'
injector_arm64_shasum = '742eecb8964e60d102416a8ddf9213e810e4af996a58e9336df7abcc6ffc9a59'


# The image reference to use for the registry that Zarf deploys into the cluster
registry_image_domain = ''
registry_image = 'library/registry'
registry_image_tag = '2.8.3'

# The image reference to use for the optional git-server Zarf deploys
gitea_image = 'gitea/gitea:1.21.5-rootless'
