[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "relocation-model=static", "-C", "strip=symbols"]

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "relocation-model=static", "-C", "strip=symbols"]
